apiVersion: v1
kind: Service
metadata:
  name: jenkins-k8s-demo-service
  labels:
    app: jenkins-k8s-demo
spec:
  type: LoadBalancer
  selector:
    app: jenkins-k8s-demo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
---
# Alternative NodePort service for Minikube
apiVersion: v1
kind: Service
metadata:
  name: jenkins-k8s-demo-nodeport
  labels:
    app: jenkins-k8s-demo
spec:
  type: NodePort
  selector:
    app: jenkins-k8s-demo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080